BaseURL = "https://kaitlynchan.github.io/cataboliccoffee/"
LanguageCode = "EN"
publishDir = "docs"
themesDir = "themes"
Title = "Catabolic Coffee"
Theme = "pacman"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "Kaitlyn Chan"

[Params]
  AuthorHomepage = "https://kaitlynchan.github.io/cataboliccoffee/"
  BottomIntroduce = "Kaitlyn Chan, Kiana Hocutt, Nicole Tan <br/> Economics Period 2"
  Description = "asdfjdlk"
  Subtitle = "Purr-fect relaxation lies ahead."

  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006.01.02"
  MonthFormat = "2006.01"
  FancyBox = true

  GoogleAnalyticsID = "UA-10147768-2"

  [Params.Strings]
    Search = "Search"
    PageNotFound = "Rip this page doesn't work >.>"
    ShowSideBar = "open me!"
    HideSideBar = "close me!"
    Categories = "Categories"
    Archive = "Archives"
    Tags = "Tags"
    TagCloud = "Tag Cloud"
    Rss = "RSS"
    TableOfContents = "Table of Contents"

[Menu]
  [[Menu.Main]]
    Name = "Home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "About"
    URL = "/about"
    Weight = 2
